### PR TITLE
Create Server Class

### PR DESCRIPTION
**Pull request by JonasBuchadas**

### CODE REVIEW

**Review by MariaAguiar — COMMENTED** [review]
Seems fine :)
Maybe put it in a server folder or split by src and inc folders?

**Comment by JonasBuchadas** [comment]
> Seems fine :) Maybe put it in a server folder or split by src and inc folders?

You're right, but I believe this change would out of scope for this issue. I think it could be implemented on the Makefile issue :)

**Review by nhorta-g — COMMENTED** [review]
Puuuuurfect!

**Review by nhorta-g — APPROVED** [review]
Puuuurfect!

**Pull request merged**
